# Generated by Django 3.2.5 on 2022-01-01 14:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendanceclass_attendance_assigntime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceclass',
            options={'verbose_name': 'Start Attendance', 'verbose_name_plural': 'Start Attendance'},
        ),
        migrations.AddField(
            model_name='attendanceclass',
            name='secret',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='class_id', chained_model_field='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='attendanceclass',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='class_id', chained_model_field='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
